import 'package:flutter/material.dart';          // generated by flutterfire configure
import 'injection_container.dart';
import 'presentation/pages/home_page.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await initDependencies();
  runApp(const MonSnatchApp());
}

class MonSnatchApp extends StatelessWidget {
  const MonSnatchApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Momon Snatch',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorSchemeSeed: const Color(0xFF6A1B9A),
        useMaterial3: true,
      ),
      home: const HomePage(),
    );
  }
}